-- Hardening: trigram search indexes, tenant column on questions, job dedupe key,
-- one precedent per response, row-level security as a second line of defence,
-- and trigger-maintained dashboard counters. Generated by drizzle-kit, then
-- hand-edited: the extension, the backfills, the policies and the triggers are
-- not expressible in the schema.
CREATE EXTENSION IF NOT EXISTS pg_trgm;--> statement-breakpoint
ALTER TABLE "rfp_questions" ADD COLUMN "workspace_id" text;--> statement-breakpoint
UPDATE "rfp_questions" q SET "workspace_id" = r."workspace_id" FROM "rfps" r WHERE r."id" = q."rfp_id" AND q."workspace_id" IS NULL;--> statement-breakpoint
ALTER TABLE "rfp_questions" ALTER COLUMN "workspace_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "rfps" ADD COLUMN "question_count" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "rfps" ADD COLUMN "drafted_count" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "rfps" ADD COLUMN "approved_count" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "rfps" ADD COLUMN "flagged_count" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "generation_jobs" ADD COLUMN "dedupe_key" text;--> statement-breakpoint
ALTER TABLE "rfp_questions" ADD CONSTRAINT "rfp_questions_workspace_id_organization_id_fk" FOREIGN KEY ("workspace_id") REFERENCES "public"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "clients_name_trgm_idx" ON "clients" USING gin ("name" gin_trgm_ops);--> statement-breakpoint
CREATE INDEX "rfp_questions_workspace_idx" ON "rfp_questions" USING btree ("workspace_id");--> statement-breakpoint
CREATE INDEX "rfp_questions_text_trgm_idx" ON "rfp_questions" USING gin ("question_text" gin_trgm_ops);--> statement-breakpoint
CREATE INDEX "rfp_questions_ref_trgm_idx" ON "rfp_questions" USING gin ("ref_no" gin_trgm_ops);--> statement-breakpoint
CREATE INDEX "rfps_title_trgm_idx" ON "rfps" USING gin ("title" gin_trgm_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "approved_answers_origin_response_uidx" ON "approved_answers" USING btree ("origin_response_id") WHERE "approved_answers"."origin_response_id" is not null;--> statement-breakpoint
CREATE UNIQUE INDEX "generation_jobs_live_dedupe_uidx" ON "generation_jobs" USING btree ("rfp_id","dedupe_key") WHERE "generation_jobs"."status" in ('queued', 'running');--> statement-breakpoint
-- Dashboard counters: recomputed for one RFP whenever its questions or responses change.
CREATE OR REPLACE FUNCTION rfp_counts_refresh(p_rfp uuid) RETURNS void LANGUAGE sql AS $fn$
  UPDATE "rfps" r
     SET "question_count" = s.q, "drafted_count" = s.d, "approved_count" = s.a, "flagged_count" = s.f
    FROM (
      SELECT count(q."id")::int AS q,
             count(s."id")::int AS d,
             count(*) FILTER (WHERE s."status" = 'approved')::int AS a,
             count(*) FILTER (WHERE s."status" = 'flagged')::int AS f
        FROM "rfp_questions" q
        LEFT JOIN "responses" s ON s."question_id" = q."id"
       WHERE q."rfp_id" = p_rfp
    ) s
   WHERE r."id" = p_rfp;
$fn$;--> statement-breakpoint
CREATE OR REPLACE FUNCTION rfp_counts_on_question() RETURNS trigger LANGUAGE plpgsql AS $fn$
BEGIN
  IF TG_OP = 'DELETE' THEN
    PERFORM rfp_counts_refresh(OLD."rfp_id");
  ELSE
    PERFORM rfp_counts_refresh(NEW."rfp_id");
    IF TG_OP = 'UPDATE' AND OLD."rfp_id" IS DISTINCT FROM NEW."rfp_id" THEN PERFORM rfp_counts_refresh(OLD."rfp_id"); END IF;
  END IF;
  RETURN NULL;
END
$fn$;--> statement-breakpoint
CREATE OR REPLACE FUNCTION rfp_counts_on_response() RETURNS trigger LANGUAGE plpgsql AS $fn$
DECLARE v_rfp uuid;
BEGIN
  SELECT "rfp_id" INTO v_rfp FROM "rfp_questions" WHERE "id" = COALESCE(NEW."question_id", OLD."question_id");
  IF v_rfp IS NOT NULL THEN PERFORM rfp_counts_refresh(v_rfp); END IF;
  RETURN NULL;
END
$fn$;--> statement-breakpoint
DROP TRIGGER IF EXISTS "rfp_questions_counts" ON "rfp_questions";--> statement-breakpoint
CREATE TRIGGER "rfp_questions_counts" AFTER INSERT OR UPDATE OF "rfp_id" OR DELETE ON "rfp_questions" FOR EACH ROW EXECUTE FUNCTION rfp_counts_on_question();--> statement-breakpoint
DROP TRIGGER IF EXISTS "responses_counts" ON "responses";--> statement-breakpoint
CREATE TRIGGER "responses_counts" AFTER INSERT OR UPDATE OF "status" OR DELETE ON "responses" FOR EACH ROW EXECUTE FUNCTION rfp_counts_on_response();--> statement-breakpoint
-- Backfill every RFP once.
SELECT rfp_counts_refresh(r."id") FROM "rfps" r;--> statement-breakpoint
-- Row-level security, enforced when a transaction has set app.org_id (withOrg) and transparent otherwise.
-- FORCE makes it apply to the table owner, which is the app role.
ALTER TABLE "rfps" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "rfps" FORCE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE POLICY "rfps_tenant" ON "rfps" USING ("workspace_id" = coalesce(nullif(current_setting('app.org_id', true), ''), "workspace_id")) WITH CHECK ("workspace_id" = coalesce(nullif(current_setting('app.org_id', true), ''), "workspace_id"));--> statement-breakpoint
ALTER TABLE "clients" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "clients" FORCE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE POLICY "clients_tenant" ON "clients" USING ("workspace_id" = coalesce(nullif(current_setting('app.org_id', true), ''), "workspace_id")) WITH CHECK ("workspace_id" = coalesce(nullif(current_setting('app.org_id', true), ''), "workspace_id"));--> statement-breakpoint
ALTER TABLE "brand_templates" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "brand_templates" FORCE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE POLICY "brand_templates_tenant" ON "brand_templates" USING ("workspace_id" = coalesce(nullif(current_setting('app.org_id', true), ''), "workspace_id")) WITH CHECK ("workspace_id" = coalesce(nullif(current_setting('app.org_id', true), ''), "workspace_id"));--> statement-breakpoint
ALTER TABLE "audit_log" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "audit_log" FORCE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE POLICY "audit_log_tenant" ON "audit_log" USING ("workspace_id" = coalesce(nullif(current_setting('app.org_id', true), ''), "workspace_id")) WITH CHECK ("workspace_id" = coalesce(nullif(current_setting('app.org_id', true), ''), "workspace_id"));--> statement-breakpoint
ALTER TABLE "kb_sources" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "kb_sources" FORCE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE POLICY "kb_sources_tenant" ON "kb_sources" USING ("workspace_id" = coalesce(nullif(current_setting('app.org_id', true), ''), "workspace_id")) WITH CHECK ("workspace_id" = coalesce(nullif(current_setting('app.org_id', true), ''), "workspace_id"));--> statement-breakpoint
ALTER TABLE "kb_entries" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "kb_entries" FORCE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE POLICY "kb_entries_tenant" ON "kb_entries" USING ("workspace_id" = coalesce(nullif(current_setting('app.org_id', true), ''), "workspace_id")) WITH CHECK ("workspace_id" = coalesce(nullif(current_setting('app.org_id', true), ''), "workspace_id"));--> statement-breakpoint
ALTER TABLE "approved_answers" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "approved_answers" FORCE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE POLICY "approved_answers_tenant" ON "approved_answers" USING ("workspace_id" = coalesce(nullif(current_setting('app.org_id', true), ''), "workspace_id")) WITH CHECK ("workspace_id" = coalesce(nullif(current_setting('app.org_id', true), ''), "workspace_id"));--> statement-breakpoint
ALTER TABLE "rfp_questions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "rfp_questions" FORCE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE POLICY "rfp_questions_tenant" ON "rfp_questions" USING ("workspace_id" = coalesce(nullif(current_setting('app.org_id', true), ''), "workspace_id")) WITH CHECK ("workspace_id" = coalesce(nullif(current_setting('app.org_id', true), ''), "workspace_id"));
